
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADJECTIVE ADVERB ARTICAL CONJUNCTION CONTRUDICTION GERUND NOUN PREPOSITION PRONOUN VERBsentence : ADJECTIVE NOUN VERB ADJECTIVE NOUN\n                | VERB CONJUNCTION ARTICAL NOUN VERB ADJECTIVE\n                | NOUN VERB ARTICAL ADJECTIVE NOUN\n                | PRONOUN ADVERB VERB CONJUNCTION PRONOUN VERB GERUND\n                | CONTRUDICTION VERB ARTICAL NOUN CONJUNCTION VERB PRONOUN\n                | NOUN PREPOSITION ARTICAL NOUN VERB ADVERB\n                | PRONOUN VERB PRONOUN CONJUNCTION PRONOUN CONTRUDICTION PRONOUN\n                | NOUN VERB PRONOUN\n                | VERB PREPOSITION VERB PREPOSITION PRONOUN VERB\n                |  NOUN ADJECTIVE VERB\n                | VERB NOUN CONJUNCTION ADJECTIVE\n                | VERB NOUN VERB NOUN NOUN\n                | VERB NOUN VERB NOUN\n                | PREPOSITION VERB PREPOSITION VERB\n                | ADJECTIVE ADJECTIVE PREPOSITION ADJECTIVE\n                | CONJUNCTION VERB CONJUNCTION NOUN VERB\n                | CONJUNCTION VERB NOUN VERB CONJUNCTION VERB PRONOUN\n                | NOUN NOUN VERB NOUN\n                | NOUN CONJUNCTION VERB CONTRUDICTION CONJUNCTION VERB\n                | NOUN ADJECTIVE PREPOSITION NOUN ADJECTIVE'
    
_lr_action_items = {'ADJECTIVE':([0,2,3,24,25,27,35,47,65,],[2,9,13,43,44,46,52,62,75,]),'VERB':([0,3,5,6,7,8,10,11,13,15,17,18,20,38,42,48,50,54,64,67,69,70,72,],[4,12,19,21,22,23,25,26,29,32,34,36,39,55,59,63,65,68,74,76,77,78,80,]),'NOUN':([0,2,3,4,19,26,30,31,33,34,37,41,44,46,51,],[3,10,11,17,38,45,47,48,50,51,54,58,60,61,66,]),'PRONOUN':([0,12,21,53,56,57,77,79,80,],[6,28,40,67,70,71,81,83,84,]),'CONTRUDICTION':([0,32,71,],[7,49,79,]),'PREPOSITION':([0,3,4,9,13,23,36,],[8,14,18,24,30,42,53,]),'CONJUNCTION':([0,3,4,17,19,39,40,49,55,58,],[5,15,16,35,37,56,57,64,69,72,]),'$end':([1,28,29,43,45,51,52,59,60,61,62,66,68,73,74,75,76,81,82,83,84,],[0,-8,-10,-15,-18,-13,-11,-14,-1,-3,-20,-12,-16,-6,-19,-2,-9,-17,-4,-7,-5,]),'ADVERB':([6,63,],[20,73,]),'ARTICAL':([12,14,16,22,],[27,31,33,41,]),'GERUND':([78,],[82,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sentence':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sentence","S'",1,None,None,None),
  ('sentence -> ADJECTIVE NOUN VERB ADJECTIVE NOUN','sentence',5,'p_sentence','lex_yacc.py',300),
  ('sentence -> VERB CONJUNCTION ARTICAL NOUN VERB ADJECTIVE','sentence',6,'p_sentence','lex_yacc.py',301),
  ('sentence -> NOUN VERB ARTICAL ADJECTIVE NOUN','sentence',5,'p_sentence','lex_yacc.py',302),
  ('sentence -> PRONOUN ADVERB VERB CONJUNCTION PRONOUN VERB GERUND','sentence',7,'p_sentence','lex_yacc.py',303),
  ('sentence -> CONTRUDICTION VERB ARTICAL NOUN CONJUNCTION VERB PRONOUN','sentence',7,'p_sentence','lex_yacc.py',304),
  ('sentence -> NOUN PREPOSITION ARTICAL NOUN VERB ADVERB','sentence',6,'p_sentence','lex_yacc.py',305),
  ('sentence -> PRONOUN VERB PRONOUN CONJUNCTION PRONOUN CONTRUDICTION PRONOUN','sentence',7,'p_sentence','lex_yacc.py',306),
  ('sentence -> NOUN VERB PRONOUN','sentence',3,'p_sentence','lex_yacc.py',307),
  ('sentence -> VERB PREPOSITION VERB PREPOSITION PRONOUN VERB','sentence',6,'p_sentence','lex_yacc.py',308),
  ('sentence -> NOUN ADJECTIVE VERB','sentence',3,'p_sentence','lex_yacc.py',309),
  ('sentence -> VERB NOUN CONJUNCTION ADJECTIVE','sentence',4,'p_sentence','lex_yacc.py',310),
  ('sentence -> VERB NOUN VERB NOUN NOUN','sentence',5,'p_sentence','lex_yacc.py',311),
  ('sentence -> VERB NOUN VERB NOUN','sentence',4,'p_sentence','lex_yacc.py',312),
  ('sentence -> PREPOSITION VERB PREPOSITION VERB','sentence',4,'p_sentence','lex_yacc.py',313),
  ('sentence -> ADJECTIVE ADJECTIVE PREPOSITION ADJECTIVE','sentence',4,'p_sentence','lex_yacc.py',314),
  ('sentence -> CONJUNCTION VERB CONJUNCTION NOUN VERB','sentence',5,'p_sentence','lex_yacc.py',315),
  ('sentence -> CONJUNCTION VERB NOUN VERB CONJUNCTION VERB PRONOUN','sentence',7,'p_sentence','lex_yacc.py',316),
  ('sentence -> NOUN NOUN VERB NOUN','sentence',4,'p_sentence','lex_yacc.py',317),
  ('sentence -> NOUN CONJUNCTION VERB CONTRUDICTION CONJUNCTION VERB','sentence',6,'p_sentence','lex_yacc.py',318),
  ('sentence -> NOUN ADJECTIVE PREPOSITION NOUN ADJECTIVE','sentence',5,'p_sentence','lex_yacc.py',319),
]
